### ISSUE TITLE
[1.13.2] Living XP Orbs crash server

### ISSUE THREAD

**Issue by Clownvin** [Clownvin/Living-Enchantment#1]
Spawning or trying to load living XP orbs crashes the server. A solution is to NOT use XP Style 2, as not using that XP Style will not cause XP orbs to be spawned.

StackTrace:
```
Exception in server tick loop

java.lang.ExceptionInInitializerError
	at net.minecraftforge.fml.network.NetworkHooks.getEntitySpawningPacket(NetworkHooks.java:68)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:413)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:318)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:270)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187278_c(PlayerChunkMapEntry.java:139)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187276_a(PlayerChunkMapEntry.java:63)
	at net.minecraft.server.management.PlayerChunkMap.func_72683_a(SourceFile:203)
	at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:250)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:308)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:151)
	at net.minecraft.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:113)
	at net.minecraft.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:64)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:233)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/WorldClient for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:39)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:51)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:214)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:76)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.loadClass(TransformingClassLoader.java:169)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	at net.minecraftforge.fml.network.FMLPlayHandler.<clinit>(FMLPlayHandler.java:35)
	... 19 more
```

I think this may be a Forge beta bug, as nothing in my code actually tries to create a WorldClient instance (afaik).

**Comment by Clownvin** [comment]
Not gunna fix. 1.12.2 is the branch. 1.15.x when?
